version: '3'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    environment:
      SURREAL_AUTH: false
      SURREAL_STRICT: false
      SURREAL_NO_BANNER: true
      SURREAL_LOG: info
      SURREAL_PATH: file://data
    entrypoint: /surreal start
    ports:
      - 8000:8000
    volumes:
      - ./data/surreal:/data

  s3storage:
    image: minio/minio:latest
    command: minio server /data --console-address ":9001"
    hostname: s3storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    restart: always
    volumes:
      - ./data/minio:/data

  createbuckets:
    image: minio/mc:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BUCKET_NAME: images
    depends_on:
      - s3storage
    entrypoint: ./scripts/bucket_setup.sh
    volumes:
      - type: bind
        source: ./scripts
        target: /scripts
        read_only: true
