version: '3'

services:
  surrealdb:
    image: surrealdb/surrealdb:1.0.0
    hostname: surrealdb
    environment:
      SURREAL_AUTH: false
      SURREAL_STRICT: false
      SURREAL_NO_BANNER: true
      SURREAL_LOG: debug
      SURREAL_PATH: file://data
    entrypoint: /surreal start
    volumes:
      - ./surreal:/data
    profiles:
      - main

  gartic-on-demand:
    image: miniaczq/gartic-on-demand
    env_file:
      - .deployment.env
    build: .
    depends_on:
      - surrealdb
    volumes:
      - ./logs:/app/logs
    profiles:
      - main

  backup:
    image: surrealdb/surrealdb:1.0.0
    entrypoint: /surreal backup http://surrealdb:8000 ./backups/latest.db
    volumes:
      - ./backups:/backups
    profiles:
      - backup
